// Builds the country flag atlas from flag-icons (MIT): every ISO 3166-1 flag rasterised by Chrome into one WebP
// grid, plus the code index. The output is committed, so builds don't need this script; re-run it after a flag-icons
// update. Usage: node scripts/flags-atlas.ts [--w 64] [--q 0.8]
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { chromium } from '@playwright/test';

const arg = (name: string, def: number) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 ? Number(process.argv[i + 1]) : def;
};
const W = arg('w', 64);
const H = Math.round((W * 3) / 4);
const Q = arg('q', 0.8);
const COLS = 16;

const root = 'node_modules/flag-icons';
const countries = JSON.parse(readFileSync(join(root, 'country.json'), 'utf8')) as { code: string; iso: boolean }[];
const codes = countries
  .filter((c) => c.iso && /^[a-z]{2}$/.test(c.code))
  .map((c) => c.code)
  .sort();
const svgs = codes.map((c) => `data:image/svg+xml;base64,${readFileSync(join(root, 'flags/4x3', `${c}.svg`)).toString('base64')}`);

const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage();
const dataUrl = await page.evaluate(
  async ({ svgs, W, H, Q, COLS }) => {
    const rows = Math.ceil(svgs.length / COLS);
    const c = document.createElement('canvas');
    c.width = COLS * W;
    c.height = rows * H;
    const g = c.getContext('2d')!;
    g.imageSmoothingQuality = 'high';
    for (let i = 0; i < svgs.length; i++) {
      const img = new Image();
      img.src = svgs[i];
      await img.decode();
      // Rasterise large first, then downscale: small direct SVG renders lose thin stripes.
      const big = document.createElement('canvas');
      big.width = W * 4;
      big.height = H * 4;
      big.getContext('2d')!.drawImage(img, 0, 0, big.width, big.height);
      g.drawImage(big, (i % COLS) * W, Math.floor(i / COLS) * H, W, H);
    }
    return c.toDataURL('image/webp', Q);
  },
  { svgs, W, H, Q, COLS },
);
await browser.close();

const webp = Buffer.from(dataUrl.split(',')[1], 'base64');
writeFileSync('src/assets/flags.webp', webp);
writeFileSync(
  'src/assets/flagIndex.ts',
  `// Generated by scripts/flags-atlas.ts from flag-icons (MIT, https://github.com/lipis/flag-icons). Do not edit.\n` +
    `/** Atlas cell size (px) and columns; codes are ISO 3166-1 alpha-2, lower case, in atlas order. */\n` +
    `export const FLAG_W = ${W};\nexport const FLAG_H = ${H};\nexport const FLAG_COLS = ${COLS};\n` +
    `export const FLAG_CODES = '${codes.join(' ')}'.split(' ');\n`,
);
console.log(`${codes.length} flags, ${W}×${H}, atlas ${(webp.length / 1024).toFixed(1)} KB`);
